#!/usr/bin/bash

# Note to future maintainer who is probably myself.  If nontrivial changes are
# required, port to a language less funky than bash.  Python probably has
# ffmpeg libraries.  Otherwise powershell would probably even work.

set -euo pipefail

debug=

for file in *; do
	if [ $debug ]; then
		echo ""
		echo "Working on $file."
	fi
	if ! echo "$file" | grep -q '.'; then
		echo "$file does not have an extension.  Skipping."
		continue
	fi
	filename="`basename "$file"`"
	extension="${filename##*.}"
	filename="${filename%.*}"

	if [ $debug ]; then
		echo "Parsing for extension $extension."
	fi
	# Define our extensions.  Anything not defined triggers a skip.
	case $extension in
		mkv) ;;
		mp4) ;;
		webm) ;;
		*)
		if [ $debug ]; then
			echo "Skipping."
		fi
		continue;;
	esac

	if [ $debug ]; then
		echo -n "Finding audio stream for ${file}..."
	fi
	# Audio line from stderr looks similar to
	#
	# 	Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
	#
	# It's a total hack how we scrape from stderr.  But it's a working
	# hack.
	#
	# ffmpeg prints file info when given only input, but returns nonzero.
	audio_stream="`ffmpeg -i "${filename}.${extension}" 2>&1 | grep -o "Audio:.*" | awk '{print $2}' | sed 's/,//'`" || true

	output_extension=""
	# Any audio stream type not defined triggers a skip.
	case $audio_stream in
		aac) output_extension="aac";;
		vorbis) output_extension="ogg";;
		opus) output_extension="opus";;
		*) echo "No output extension defined for $audio_stream."
			continue;;
	esac
	if [ $debug ]; then
		echo "Output extension set to $output_extension."
	fi
	echo "Converting $file to $filename.$output_extension"
	command="ffmpeg -y -i \"$file\" -vn -acodec copy \"$filename.$output_extension\""
	if [ $debug ]; then
		echo "$command"
	fi
	eval "$command"
done
